version: '3.8'

services:
  app:
    container_name: appseed_app
    build: .
    restart: always
    command: >
      gunicorn core.wsgi:application 
      --bind 0.0.0.0:8000 
      --workers 4 
      --timeout 120
    volumes:
      - .:/app  # Optional for dev, remove for production
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - web_network

  db:
    container_name: postgres_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - .env
    networks:
      - web_network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
