# Generated by Django 5.1.7 on 2025-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="picture",
            field=models.ImageField(
                default="candidate_pics/default.jpg", upload_to="candidate_pics/"
            ),
        ),
    ]
