# Generated by Django 5.1.7 on 2025-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_candidate_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="picture",
            field=models.ImageField(
                default="candidate_pics/default", upload_to="candidate_pics/"
            ),
        ),
    ]
