# Generated by Django 5.1.7 on 2025-04-09 21:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_candidate_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="image/upload/v1743849300/default_kjaryj.jpg",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
